apiVersion: v1
kind: Service
metadata:
  name: soloud-was
  labels:
    app: soloud-was
spec:
  type: ClusterIP 
  selector:
    app: soloud-was
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

